# Paths
data_path: /Users/helenerousset/OneDrive - Capgemini/Documents/Illuin/squad1.1
train_filename: train-v1.1.json
test_filename: dev-v1.1.json

# Chosen dataset : train or test
dataset: test

# Model : TFIDF or BERT
model: BERT
# Only for BERT model
load_context: true
context_pickle_name: test_context

# Metrics
rank: 10

# Inference question index (only for inference)
question_idx: 10
